name: Enforce Pull request format

# TYPE="feat|fix|refactor|doc|chore|ci|style|test|perf|revert"

env:
  NODE_VER: '20.x'

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev
      - docs

jobs:
  pr_format_check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write 
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v4
    
    
    #   - name: Check title
    #     run: |
    #         title=$(gh pr view ${{ github.event.pull_request.number }} --json title --jq '.title')
    #         # Example check (adjust to your specific convention):
    #         if [[ ! $title =~ ^([a-z]+)(\(.+\))?!?: .+$ ]]; then
    #         echo "::error::Pull request title does not follow Conventional Commits format"
    #         exit 1
    #         fi

      - name: Check title
        run: |
            title=$(gh pr view ${{ github.event.pull_request.number }} --json title --jq '.title')

            echo "$title"
            
            # Define allowed Conventional Commit types
            allowed_types="feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"

            # Check if title matches the pattern: <type>: #<issue_number>
            if ! echo "$title" | grep -Eq "^($allowed_types)(?:\(.+\))?: (?:#[0-9]+|.*)$"; then
            echo "::error::Pull request title does not follow the required format"
            exit 1
            fi

      - name: Check description
        run: |
            body=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq '.body')
            if [[ ! $body =~ "## Description" ]] || [[ ! $body =~ "## Changes Made" ]] || [[ ! $body =~ "## Related Issue" ]]; then
            echo "::error::Pull request description is missing required sections (Description, Changes Made, Related Issue)"
            exit 1
            fi
            if [[ ! $body =~ "- \[ \]" ]]; then
            echo "::error::Pull request description is missing checklist items under 'Changes Made'"
            exit 1
            fi
            if [[ ! $body =~ "Closes #[0-9]+" ]]; then
            echo "::error::Pull request description's 'Related Issue' section does not follow the 'Closes #<issue_number>' format"
            exit 1
            fi
      
      - name: Check description
        run: |
          body=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq '.body')

          # Check for required sections
          if ! echo "$body" | grep -q "## Description"; then
            echo "::error::Pull request description is missing the 'Description' section"
            exit 1
          fi
          if ! echo "$body" | grep -q "## Changes Made"; then
            echo "::error::Pull request description is missing the 'Changes Made' section"
            exit 1
          fi
          if ! echo "$body" | grep -q "## Related Issue"; then
            echo "::error::Pull request description is missing the 'Related Issue' section"
            exit 1
          fi

          # Check for checklist items under "Changes Made"
          if ! echo "$body" | grep -q "- \[ \]"; then
            echo "::error::Pull request description is missing checklist items under 'Changes Made'"
            exit 1
          fi

          # Check for "Closes #" format in "Related Issue"
          if ! echo "$body" | grep -q "Closes #[0-9]+"; then
            echo "::error::Pull request description's 'Related Issue' section does not follow the 'Closes #<issue_number>' format"
            exit 1
          fi