name: Enfore PR format

# TYPE="feat|fix|refactor|doc|chore|ci|style|test|perf|revert"

env:
  NODE_VER: '20.x'

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev
      - docs

jobs:
  pr_format_check:
    runs-on: psc-dl-mac
    steps:
      - uses: actions/checkout@v4
