name: Enforce Pull request format

# TYPE="feat|fix|refactor|doc|chore|ci|style|test|perf|revert"

env:
  NODE_VER: '20.x'

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev
      - docs

jobs:
  pr_format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
    #   - name: Check title
    #     run: |
    #         title=$(gh pr view ${{ github.event.pull_request.number }} --json title --jq '.title')
    #         # Example check (adjust to your specific convention):
    #         if [[ ! $title =~ ^([a-z]+)(\(.+\))?!?: .+$ ]]; then
    #         echo "::error::Pull request title does not follow Conventional Commits format"
    #         exit 1
    #         fi

      - name: Check title
        run: |
            title=$(gh pr view ${{ github.event.pull_request.number }} --json title --jq '.title')
            if [[ ! $title =~ ^feat: #[0-9]+$ ]]; then
            echo "::error::Pull request title does not follow the required 'feat: #<issue_number>' format"
            exit 1
            fi

      - name: Check description
        run: |
            body=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq '.body')
            if [[ ! $body =~ "## Description" ]] || [[ ! $body =~ "## Changes Made" ]] || [[ ! $body =~ "## Related Issue" ]]; then
            echo "::error::Pull request description is missing required sections (Description, Changes Made, Related Issue)"
            exit 1
            fi
            if [[ ! $body =~ "- \[ \]" ]]; then
            echo "::error::Pull request description is missing checklist items under 'Changes Made'"
            exit 1
            fi
            if [[ ! $body =~ "Closes #[0-9]+" ]]; then
            echo "::error::Pull request description's 'Related Issue' section does not follow the 'Closes #<issue_number>' format"
            exit 1
            fi